Ottosson93/SomniatProject

SomniatProject/Assets/Scenes/PrototypeScene.unity

Added and image that is blank and inactive for testing purposes.

Added Image to PauseMenuView

---

SomniatProject/Assets/Prefabs/NonPlayerCharacters/OurGruntPrefab.prefab
SomniatProject/Assets/Prefabs/PlayerCharacter/DogPolyart Variant.prefab
SomniatProject/Assets/Scripts/Player/ThirdPersonController.cs

Fanns två objekt som har en collider i sig hos en enemygrunt. Tog bort character controller sålänge, kommer nog behöva den senare för animationerna, ska testa iallafall vad som är bäst.

Fixat så att enemy tar skada bara en gång

---

SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack1.asset
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack1.asset.meta
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack1.overrideController
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack1.overrideController.meta
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack2.asset
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack2.asset.meta
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack2.overrideController
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack2.overrideController.meta
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack3.asset
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack3.asset.meta
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack3.overrideController
SomniatProject/Assets/Data/Attacks/EnemyMeleeAttack3.overrideController.meta
SomniatProject/Assets/Prefabs/NonPlayerCharacters/OurGruntPrefab.prefab
SomniatProject/Assets/Scripts/AI/BehaviorTrees/CheckEnemyInAttackRange.cs
SomniatProject/Assets/Scripts/AI/BehaviorTrees/GuardBT.cs
SomniatProject/Assets/Scripts/AI/BehaviorTrees/GuardMeleeBT.cs
SomniatProject/Assets/Scripts/AI/BehaviorTrees/TaskAttack.cs
SomniatProject/Assets/Textures and Models/Mini Legion Grunt PBR HP Polyart/Animations/Grunt.controller

varenda attack har sin egen damage som läggs på genom combon, Nu borde till och med lucidity metern ändras efter animationen och ej slår från lång bort som sista tick utanför range

Skapat combos för enemy

---

SomniatProject/Assets/Scenes/DungeonA.unity
SomniatProject/Assets/Scripts/DungeonPCG/CorridorGenerator.cs
SomniatProject/Assets/Scripts/DungeonPCG/DungeonGenerator.cs
SomniatProject/Assets/Scripts/Items/PickUpScript.cs
SomniatProject/Assets/Scripts/Player/ThirdPersonController.cs

Fixed the problem where corridors didn't connect accurately. It's not perfect yet, but closer

Corridors have been fixed.

---

SomniatProject/Assets/Prefabs/DungeonPCG/ManualRooms/Start Room.prefab
SomniatProject/Assets/Prefabs/Props/Pickup_fireball variant.prefab
SomniatProject/Assets/Prefabs/Props/Pickup_fireball variant.prefab.meta
SomniatProject/Assets/Prefabs/Spells/Empty Spell.prefab
SomniatProject/Assets/Prefabs/Spells/Empty Spell.prefab.meta
SomniatProject/Assets/Scripts/Items/Item.cs
SomniatProject/Assets/Scripts/Items/SpellItem.cs
SomniatProject/Assets/Scripts/Items/SpellItem.cs.meta
SomniatProject/Assets/Scripts/Spells/None.asset
SomniatProject/Assets/Scripts/Spells/None.asset.meta
SomniatProject/Assets/Scripts/Spells/SpellAttackSystem.cs
SomniatProject/Assets/Textures and Models/CatBorg Studio/3D Dungeon Lowpoly Pack/Materials/M_Imphenzia_LowPollyStyle.mat

Made a template for conumsable spell items. Added Spell Item class and added code to Item class.

Added Spell Items

---

SomniatProject/Assets/Scripts/Items/Item.cs
SomniatProject/Assets/Scripts/Items/SpellItem.cs

Had different variable name on my latest commit. Caused error. Fixed.

Fixed variable name of SpellAttackSystem

---

SomniatProject/Assets/Scenes/PrototypeScene.unity
SomniatProject/Assets/Scripts/DungeonPCG/CorridorGenerator.cs
SomniatProject/Assets/Scripts/DungeonPCG/Doorway.cs
SomniatProject/Assets/Scripts/DungeonPCG/Doorway.cs.meta
SomniatProject/Assets/Scripts/DungeonPCG/DungeonCreator.cs
SomniatProject/Assets/Scripts/DungeonPCG/DungeonGenerator.cs
SomniatProject/Assets/Scripts/DungeonPCG/PCGObjects.cs
SomniatProject/Assets/Scripts/DungeonPCG/PCGObjects.cs.meta
SomniatProject/Assets/Scripts/DungeonPCG/RNode.cs

Pillars are now placed at corridor entrances. I also cleaned up some debug logs.

Pillars have been Procedurally placed

---

SomniatProject/Assets/Scripts/Items/PickUpScript.cs
SomniatProject/Assets/Scripts/Items/Potion.cs
SomniatProject/Assets/Scripts/Items/Relic.cs
SomniatProject/Assets/Scripts/Items/SpellItem.cs

Re added fading in of the button and improved pick-up script.
Om ej behovs ta bort funktion vid behov.

Improved Pick-up Script

---

SomniatProject/Assets/Hovl Studio.meta
SomniatProject/Assets/Hovl Studio/Magic effects pack.meta
SomniatProject/Assets/Hovl Studio/Magic effects pack/Materials/Arrow1.mat
SomniatProject/Assets/Hovl Studio/Magic effects pack/Materials/Circle.mat
SomniatProject/Assets/Hovl Studio/Magic effects pack/Materials/Flare.mat
SomniatProject/Assets/Hovl Studio/Magic effects pack/Materials/Star.mat
SomniatProject/Assets/Hovl Studio/Magic effects pack/Prefabs/Character auras/Buff.prefab
SomniatProject/Assets/Prefabs/PlayerCharacter/DogPolyart Variant.prefab
SomniatProject/Assets/Prefabs/Spells/Berserk.meta
SomniatProject/Assets/Prefabs/Spells/Berserk/Berserk.prefab
SomniatProject/Assets/Prefabs/Spells/Berserk/Berserk.prefab.meta
SomniatProject/Assets/Scripts/Player/Player.cs
SomniatProject/Assets/Scripts/Spells/Berserk.asset
SomniatProject/Assets/Scripts/Spells/Berserk.asset.meta
SomniatProject/Assets/Scripts/Spells/Spell.cs
SomniatProject/Assets/Scripts/Spells/SpellAttackSystem.cs
SomniatProject/Assets/Scripts/Spells/SpellScriptableObject.cs

Implemented logic and VFX for the Berserk ability

Implemented Berserk ability

---

SomniatProject/Assets/Prefabs/DungeonPCG/ManualRooms/Corridor Room.prefab
SomniatProject/Assets/Prefabs/DungeonPCG/ManualRooms/Corridor Room.prefab.meta
SomniatProject/Assets/Prefabs/DungeonPCG/ManualRooms/Start Room.prefab
SomniatProject/Assets/Prefabs/DungeonPCG/Props/Horizontall Wall 5.prefab
SomniatProject/Assets/Prefabs/DungeonPCG/Props/Pillar.prefab
SomniatProject/Assets/Prefabs/DungeonPCG/Props/Pillar.prefab.meta
SomniatProject/Assets/Prefabs/UI/Shop/Shop.prefab
SomniatProject/Assets/Scenes/PrototypeScene.unity
SomniatProject/Assets/Scripts/DungeonPCG/CorridorGenerator.cs
SomniatProject/Assets/Scripts/DungeonPCG/DungeonCreator.cs
SomniatProject/Assets/Scripts/DungeonPCG/DungeonGenerator.cs
SomniatProject/Assets/Scripts/DungeonPCG/PCGObjects.cs
SomniatProject/Assets/Scripts/DungeonPCG/RNode.cs
SomniatProject/Assets/Textures and Models/LowPolyDungeonsLite/Materials/LowPolyDungeonsLite_MAIN.mat
SomniatProject/Assets/Textures and Models/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_HDRP_v1.0.unitypackage.meta
SomniatProject/Assets/Textures and Models/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_URP_v1.0.unitypackage.meta

Re-creates dungeon if manual rooms are not insterted. Created more corridors. Made changes to walls.

Made changes to dungeon creation

---

SomniatProject/Assets/Blink/Art/Animations/Animations_Starter_Pack/Combat/Trails.controller
SomniatProject/Assets/Blink/Art/Animations/Animations_Starter_Pack/Combat/Trails.controller.meta
SomniatProject/Assets/Resources/Prefabs/Items/1 coin.prefab
SomniatProject/Assets/Resources/Prefabs/Items/10 coins.prefab
SomniatProject/Assets/Resources/Prefabs/Items/2 coins.prefab
SomniatProject/Assets/Resources/Prefabs/Items/5 coins.prefab
SomniatProject/Assets/Scenes/PrototypeScene.unity
SomniatProject/Assets/Scripts/Items/Money.cs
SomniatProject/Assets/Scripts/Status effects/ParticleSystemController.cs
SomniatProject/Assets/Scripts/UI/Shop/ShopManagerScript.cs

Coin amount is now being sent to the shopmanagerscript properly

Fixed coin pickup

---

SomniatProject/Assets/Resources/Prefabs/PlayerCharacter/DogPolyart Variant.prefab
SomniatProject/Assets/Scripts/Player/FireWeapon.cs
SomniatProject/Assets/Scripts/Player/Player.cs
SomniatProject/Assets/Scripts/Player/ThirdPersonController.cs
SomniatProject/Assets/Scripts/Props/AttackSO.cs
SomniatProject/Assets/Scripts/Spells/Spell.cs
SomniatProject/Assets/Textures and Models/LowPolyDungeonsLite/LowPolyDungeonsLite_2020.3.0_HDRP_v1.1.unitypackage.meta
SomniatProject/Assets/Textures and Models/LowPolyDungeonsLite/LowPolyDungeonsLite_2020.3.0_URP_v1.1.unitypackage.meta
SomniatProject/Assets/Textures and Models/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_HDRP_v1.0.unitypackage.meta
SomniatProject/Assets/Textures and Models/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_URP_v1.0.unitypackage.meta

Attack damage, attackspeed, movement speed, ranged attackspeed, spell damage, lucidity & max lucidity now updating with character stats

Stats linked to player

---

SomniatProject/Assets/Scripts/Items/DropSystem/ItemDropSystem.cs

Fixed drop logic

---

SomniatProject/Assets/Scripts/Items/Chest.cs
SomniatProject/Assets/Scripts/Spells/Spell.cs

Chest rotation + spell sounds removed from Spell script

More fixes for main

---

SomniatProject/Assets/Scripts/Player/Player.cs
SomniatProject/Assets/Scripts/Spells/Berserk.asset
SomniatProject/Assets/Scripts/Spells/Spell.cs

Reset armor amount after each berserk use

Fixed armor bug in Berserk ability

---

SomniatProject/Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset
SomniatProject/Assets/Resources/Prefabs/DungeonPCG/ManualRooms/Start Room.prefab
SomniatProject/Assets/Scripts/Player/LucidityPostProcess.cs
SomniatProject/Assets/Scripts/Player/PostProcess.cs
SomniatProject/fmod_editor.log

It starts on the correct position and is smaller.

Fix Lucid Circle Size

---

SomniatProject/Assets/Scripts/Spells/Spell.cs
SomniatProject/Assets/Scripts/Status effects/StunEffect.cs
SomniatProject/Assets/Textures and Models/Mini Legion Grunt PBR HP Polyart/Animations/Grunt.controller
SomniatProject/Assets/Textures and Models/RPGMonsterPartnersPBRPolyart/Animators/Beholder.controller
SomniatProject/fmod_editor.log

Added a stunLoop animation to the two basic enemy types, still some logic to sort out, probably in their AI

Added stun animation to grunt and ranged enemy

---

SomniatProject/Assets/Resources/ItemDropData.csv
SomniatProject/Assets/Resources/Prefabs/Items/ItemDropData.csv
SomniatProject/Assets/Scripts/Player/Player.cs
SomniatProject/Assets/Textures and Models/DogKnight/Animator/DogControl.controller

Fixed spell error, attack speed and dexterity value

Fixed spell error, attack speed and dexterity value

---

SomniatProject/Assets/Scenes/PrototypeScene.unity
SomniatProject/Assets/Scripts/Player/Player.cs
SomniatProject/Assets/Scripts/UI/Menus/MenuManager.cs

Fixed stats to modify power of character properly

Playtest build balance

---

SomniatProject/Assets/Scenes/PrototypeScene.unity
SomniatProject/Assets/Scripts/Items/CakeRelic.asset

Removed item templates from shop

Minor shop fix

---

SomniatProject/Assets/Resources/Prefabs/Bullets/Enemy Buillet/EnemyBullet.prefab
SomniatProject/Assets/Resources/Prefabs/Bullets/Enemy Buillet/EnemyBullet.prefab.meta
SomniatProject/Assets/Resources/Prefabs/Bullets/EnemyBulletPrefab.prefab
SomniatProject/Assets/Resources/Prefabs/NonPlayerCharacters/RangedEnemyPrefab.prefab
SomniatProject/Assets/Scenes/PrototypeScene.unity
SomniatProject/Assets/Scripts/Props/EnemyBullet.cs
SomniatProject/Assets/Textures and Models/FreeSportsKIt_SA/Models/tennis_ball.fbx.meta

Added tennis ball in lucid layer

Updated enemy bullet

---

SomniatProject/Assets/Resources/Prefabs/DungeonPCG/ManualRooms/Battle Room.prefab
SomniatProject/Assets/Resources/Prefabs/DungeonPCG/ManualRooms/Boss Room.prefab
SomniatProject/Assets/Resources/Prefabs/DungeonPCG/ManualRooms/Corridor Room.prefab
SomniatProject/fmod_editor.log

- add lucid mesh on manual floors

fix floors
